# Generated by Django 4.1.4 on 2022-12-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_consent',
            new_name='consent',
        ),
    ]
