# Generated by Django 4.1.5 on 2023-01-06 17:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_consent_user_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(1990, 5, 27), verbose_name='data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='education_institution',
            field=models.BooleanField(default=False, verbose_name='vínculo com instituição de ensino?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='profissão'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
