# Generated by Django 4.1.1 on 2022-09-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='sobrenome')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'coletânea',
                'verbose_name_plural': 'coletâneas',
            },
        ),
        migrations.CreateModel(
            name='OriginalFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragment', models.TextField(verbose_name='fragmento')),
            ],
            options={
                'verbose_name': 'fragmento original',
                'verbose_name_plural': 'fragmentos originais',
                'db_table': 'corpus_original_fragment',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=255, null=True, verbose_name='cidade')),
                ('state_province', models.CharField(max_length=255, null=True, verbose_name='estado/província')),
                ('country', models.CharField(max_length=255, verbose_name='país')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='corpus.place')),
            ],
            options={
                'verbose_name': 'editora',
                'verbose_name_plural': 'editoras',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='sobrenome')),
            ],
            options={
                'verbose_name': 'tradutor',
                'verbose_name_plural': 'tradutores',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(null=True, verbose_name='ano')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('authors', models.ManyToManyField(to='corpus.author', verbose_name='autores')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(null=True, verbose_name='ano')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('authors', models.ManyToManyField(blank=True, to='corpus.translator', verbose_name='autores')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='corpus.collection', verbose_name='coletânea')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='corpus.publisher', verbose_name='editora')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corpus.work', verbose_name='original')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
            },
        ),
        migrations.CreateModel(
            name='TranslatedFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragment', models.TextField(verbose_name='fragmento')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corpus.originalfragment', verbose_name='original')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corpus.translation', verbose_name='tradução')),
            ],
            options={
                'verbose_name': 'fragmento traduzido',
                'verbose_name_plural': 'fragmentos traduzidos',
                'db_table': 'corpus_translated_fragment',
            },
        ),
        migrations.AddField(
            model_name='originalfragment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corpus.work', verbose_name='obra'),
        ),
        migrations.AddField(
            model_name='collection',
            name='authors',
            field=models.ManyToManyField(blank=True, to='corpus.translator', verbose_name='autores'),
        ),
        migrations.AddField(
            model_name='collection',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='corpus.publisher', verbose_name='editora'),
        ),
    ]
