# Generated by Django 4.1.1 on 2022-09-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragment', models.TextField(verbose_name='fragmento')),
            ],
            options={
                'verbose_name': 'fragmento original',
                'verbose_name_plural': 'fragmentos originais',
                'db_table': 'corpus_original_fragment',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state_province', models.CharField(max_length=255, null=True, verbose_name='estado/província')),
                ('country', models.CharField(max_length=255, verbose_name='país')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='local', to='corpus.place')),
            ],
            options={
                'verbose_name': 'editora',
                'verbose_name_plural': 'editoras',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='ano'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(null=True, verbose_name='ano')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('authors', models.ManyToManyField(to='corpus.author', verbose_name='autores')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='editora', to='corpus.publisher')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original', to='corpus.work')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
            },
        ),
        migrations.CreateModel(
            name='TranslatedFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragment', models.TextField(verbose_name='fragmento')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original', to='corpus.originalfragment')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tradução', to='corpus.translation')),
            ],
            options={
                'verbose_name': 'fragmento traduzido',
                'verbose_name_plural': 'fragmentos traduzidos',
                'db_table': 'corpus_translated_fragment',
            },
        ),
        migrations.AddField(
            model_name='originalfragment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='obra', to='corpus.work'),
        ),
    ]
