# Generated by Django 4.1.1 on 2022-09-28 23:00

from django.db import migrations
import pandas as pd

import logging

logger = logging.getLogger(__name__)


def load_romances(apps, schema_editor):
    Work = apps.get_model('corpus', 'Work')
    Translation = apps.get_model('corpus', 'Translation')
    OriginalFragment = apps.get_model('corpus', 'OriginalFragment')
    TranslatedFragment = apps.get_model('corpus', 'TranslatedFragment')

    df_pt = pd.read_csv('corpus/migrations/data/romances_pt.csv')
    df_en = pd.read_csv('corpus/migrations/data/romances_en.csv')

    for code, indices in df_pt.groupby('work_id').groups.items():
        work = Work.objects.filter(code=code).get()
        translations = []
        for _, row in df_pt.loc[indices, :].iterrows():
            original = OriginalFragment(work=work, fragment=row['line'])
            original.save()
            original.refresh_from_db()

            for fragment, code in df_en.loc[lambda d: (d['aligned_id'] == row['aligned_id'])
                                            & (d['work_id'].str.startswith(row['work_id'][:5])),
                                            ['line', 'work_id']].values:
                try:
                    work_ = Translation.objects.filter(code=code).get()
                except Translation.DoesNotExist:
                    logger.debug(
                        f"Could not find Translation with code {code}")
                else:
                    translations.append(TranslatedFragment(
                        work=work_, fragment=fragment, original=original))

        TranslatedFragment.objects.bulk_create(translations)


def load_short_stories(apps, schema_editor):
    Work = apps.get_model('corpus', 'Work')
    Collection = apps.get_model('corpus', 'Collection')
    Translation = apps.get_model('corpus', 'Translation')
    OriginalFragment = apps.get_model('corpus', 'OriginalFragment')
    TranslatedFragment = apps.get_model('corpus', 'TranslatedFragment')


def rollback_romances(apps, schema_editor):
    OriginalFragment = apps.get_model('corpus', 'OriginalFragment')
    TranslatedFragment = apps.get_model('corpus', 'TranslatedFragment')

    TranslatedFragment.objects.filter(
        original__work__code__startswith='RO').delete()
    OriginalFragment.objects.filter(work__code__startswith='RO').delete()


def rollback_short_stories(apps, schema_editor):
    OriginalFragment = apps.get_model('corpus', 'OriginalFragment')
    OriginalFragment.objects.filter(work__code__startswith='CO').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20220928_0052'),
    ]

    operations = [
        migrations.RunPython(load_romances, rollback_romances),
        migrations.RunPython(load_short_stories, rollback_short_stories),
    ]
