# Generated by Django 4.1.4 on 2022-12-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220928_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='corpus.place', verbose_name='local'),
        ),
    ]
